### ISSUE TITLE
Header Cards disapears every night

### ISSUE THREAD

**Issue by cweakland** [gadgetchnnel/lovelace-header-cards#16]
I used to see this on occasion, but now it has become a nightly occurrence. It happens each night some time after 10pm and 7am (when I am sleeping). Here is what my header card looks like when its functioning properly (This is a 7" RaspberryPi touch screen running chromium-browser). Does my kiosk_mode addon play into this somehow? 

![image](https://github.com/user-attachments/assets/caff0770-c266-4e83-8630-5d1a3dd37f2a)

In the morning this is what it looks like, the header cards are missing:

![image](https://github.com/user-attachments/assets/3bf6ef56-6221-4c4b-814b-1611246a1697)

My here is my relevant configuration:
```
kiosk_mode:
  hide_assistant: true
  hide_search: true
  hide_menubutton: false
  hide_sidebar: false
  hide_account: true
  hide_notifications: true
header_cards:
  replace_tabs: true
  justify_content: space-between
  cards:
    - type: markdown
      card_mod:
        style: |
          ha-card {
            background: rgba(0,0,0,0);
            font-size: 1.2em;
          }
      content: >
        {{ as_timestamp(states('sensor.date_time_iso'),default=None) |
        timestamp_custom('%-I:%M %p',default=None) }}
    - type: markdown
      card_mod:
        style: |
          ha-card {
            background: rgba(0,0,0,0);
            font-size: 1.2em;
          }
      content: >
        {{ as_timestamp(states('sensor.date_time_iso'),default=None) |
        timestamp_custom('%A,  %B %-d',default=None) }}
views:
```

**Comment by warmfire540** [comment]
I was having these same issues.. I did make my own version of the header card after using this one for a bit.  

My card works slightly different and is not setup globally like this one, but it's very quick and is based on labels/areas instead of config in the card.

https://community.home-assistant.io/t/toolbar-status-chips-card-with-sticky-header-and-driven-by-entities/825075

https://github.com/warmfire540/toolbar-status-chips

**Comment by shaiger** [comment]
Interesting. My scenario requires an actual card (a custom:button-card if to be specific), so chips alone would not be enough.

**Comment by warmfire540** [comment]
Sounds good, this used button-card behind the scenes.  But makes sense

**Comment by cweakland** [comment]
I am no longer seeing this issue, however, I have cleaned up/minimized my configuration. Perhaps it was never a Header Card problem. 

![Image](https://github.com/user-attachments/assets/fbdc9a8a-c5e6-428d-a7be-620663094733)

Here is my fill code if someone stumbles across this and wonders how its done
Code:


```

kiosk_mode:
  hide_assistant: true
  hide_search: true
  hide_menubutton: true
  hide_sidebar: true
  hide_account: true
  hide_notifications: true
header_cards:
  replace_tabs: false
  justify_content: right
  cards:
    - type: custom:mushroom-chips-card
      card_mod:
        style: |
          ha-card {
            --chip-font-size: 0.5em;
          } 
      chips:
        - type: template
          entity: sensor.time
          icon: null
          content: >
            {{ as_timestamp(states('sensor.date_time_iso'),default=None) |
            timestamp_custom('%A,  %B %-d',default=None) }}
          tap_action:
            action: none
          card_mod:
            style: |
              ha-card {
                --chip-border-width: 0px;
              }   
        - type: template
          entity: sensor.time
          icon: null
          content: >
            {{ as_timestamp(states('sensor.date_time_iso'),default=None) |
            timestamp_custom('%-I:%M %p',default=None) }}
          tap_action:
            action: none
          card_mod:
            style: |
              ha-card {
                --chip-border-width: 0px;
              }            
views:
  - type: sections
    sections:
      - type: grid
        cards:
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-title-card
                title: ''
                subtitle: Weather
                card_mod:
                  style: |
                    ha-card {
                      padding-right: 0px !important;
                      padding-left: 0px !important;
                      padding-bottom: 0px !important;
                      padding-top: 0px !important;
                    }
                    .subtitle {
                      color: white !important;
                    }
              - show_current: true
                show_forecast: true
                type: weather-forecast
                entity: weather.ellicott_city
                forecast_type: daily
                secondary_info_attribute: wind_speed
              - type: custom:mushroom-title-card
                title: ''
                subtitle: Security / Sensors
                card_mod:
                  style: |
                    ha-card {
                      padding-right: 0px !important;
                      padding-left: 0px !important;
                      padding-bottom: 0px !important;
                      padding-top: 0px !important;
                    }
                    .subtitle {
                      color: white !important;
                    }
              - type: horizontal-stack
                cards:
                  - type: custom:mushroom-template-card
                    primary: Door Locks
                    secondary: '{{  states(''lock.all_locks'') | capitalize }}'
                    icon: >-
                      {{ 'mdi:lock' if states('lock.all_locks') == 'locked' else
                      'mdi:lock-open' }}
                    icon_color: >-
                      {{ 'green' if states('lock.all_locks') == 'locked' else
                      'red' }}
                    badge_icon: ''
                    fill_container: false
                    tap_action:
                      action: more-info
                    entity: lock.all_locks
                  - type: custom:mushroom-template-card
                    entity: binary_sensor.all_security_sensors_status
                    primary: Sensor Status
                    secondary: >-
                      {{ 'Safe' if
                      states('binary_sensor.all_security_sensors_status') ==
                      'off' else 'Unsafe' }}
                    icon_color: >-
                      {{ 'green' if
                      states('binary_sensor.all_security_sensors_status') ==
                      'off' else 'red' }}
                    icon: >-
                      {{ 'mdi:alert-circle' if
                      states('binary_sensor.all_security_sensors_status') ==
                      'on' else 'mdi:check-circle' }}
                    tap_action:
                      action: more-info
              - type: horizontal-stack
                cards:
                  - type: custom:mushroom-template-card
                    primary: '{{ states(''sensor.trash_pickup'') }}'
                    icon: mdi:trash-can
                    icon_color: >-
                      {{ 'red' if 'Trash Tomorrow' in
                      states('sensor.trash_pickup') else 'red' if 'Trash Today'
                      in states('sensor.trash_pickup') else 'blue' }}
                  - type: custom:mushroom-template-card
                    primary: '{{ states(''sensor.recycling_pickup'') }}'
                    icon: mdi:recycle
                    icon_color: >-
                      {{ 'red' if 'Recycle Tomorrow' in
                      states('sensor.recycling_pickup') else 'red' if 'Recycle
                      Today' in states('sensor.recycling_pickup') else 'blue' }}
                    card_mod:
                      style:
                        mushroom-state-info$: |
                          span.primary {
                          white-space: normal !important;
                          }
            columns: 1
      - type: grid
        cards:
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-title-card
                title: ''
                subtitle: Light Scenes
                card_mod:
                  style: |
                    ha-card {
                      padding-right: 0px !important;
                      padding-left: 0px !important;
                      padding-bottom: 0px !important;
                      padding-top: 0px !important;
                    } 
                    .subtitle {
                      color: white !important;
                    }
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: scene.movie
                    show_entity_picture: true
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
                  - type: custom:button-card
                    entity: scene.bright
                    show_entity_picture: true
                    icon: mdi:lightbulb-on
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: scene.daytime
                    name: Day/Night Light
                    show_entity_picture: true
                    icon: mdi:theme-light-dark
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
                  - type: custom:button-card
                    entity: scene.relax
                    show_entity_picture: true
                    icon: mdi:lightbulb-on-50
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
              - type: horizontal-stack
                cards:
                  - type: custom:button-card
                    entity: scene.bedtime
                    show_entity_picture: true
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
                  - type: custom:button-card
                    entity: scene.lights_off
                    show_entity_picture: true
                    icon: mdi:lightbulb-outline
                    tap_action:
                      action: toggle
                    styles:
                      card:
                        - height: 129px
                        - '--mdc-ripple-color': white
                        - '--mdc-ripple-press-opacity': 0.75
            columns: 1
    icon: mdi:home
    cards: []
    badges: []
    max_columns: 4
    dense_section_placement: false
  - type: sections
    icon: mdi:sun-thermometer
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Radar
          - camera_view: auto
            type: picture-glance
            image: https://demo.home-assistant.io/stub_config/kitchen.png
            entities: []
            camera_image: camera.radar_weather_gov
      - type: grid
        cards:
          - type: heading
            heading: Weather Sensors
          - graph: line
            type: sensor
            entity: sensor.outside_temp
            detail: 1
          - graph: line
            type: sensor
            entity: sensor.rain_24hrs
            detail: 1
          - graph: line
            type: sensor
            entity: sensor.allergy_index_today
            detail: 1
            name: Allergy Index
          - type: tile
            entity: sensor.uv_index
          - type: tile
            entity: sensor.outside_humidity
          - type: tile
            entity: sensor.wind_gust
          - type: tile
            entity: sensor.pool_temp
    max_columns: 4
    title: Weather
    cards: []
  - type: panel
    cards:
      - type: custom:frigate-card
        cameras:
          - camera_entity: camera.frontyard
            live_provider: image
            go2rtc:
              modes:
                - mjpeg
            image:
              entity_parameters: width=640&height=480
          - camera_entity: camera.basement
            live_provider: image
            go2rtc:
              modes:
                - mjpeg
            image:
              entity_parameters: width=640&height=480
          - camera_entity: camera.backyard
            live_provider: image
            go2rtc:
              modes:
                - mjpeg
            image:
              entity_parameters: width=640&height=480
          - camera_entity: camera.backyard_shed
            live_provider: image
            go2rtc:
              modes:
                - mjpeg
            image:
              entity_parameters: width=640&height=480
          - camera_entity: camera.driveway
            live_provider: image
            go2rtc:
              modes:
                - mjpeg
            image:
              entity_parameters: width=640&height=480
        menu:
          style: none
        live:
          controls:
            builtin: true
            title:
              mode: none
            thumbnails:
              mode: none
          draggable: false
          transition_effect: none
        view:
          timeout_seconds: 60
        profiles: []
        dimensions:
          aspect_ratio_mode: dynamic
    icon: mdi:cctv
    title: Cameras


```
