### ISSUE TITLE
Odd behaviour when usied in narrow (phone) screen

### ISSUE THREAD

**Issue by sesquipedality** [gadgetchnnel/lovelace-header-cards#4]
I would like the header cards to hide themselves when there is not enough vertical room to show them. Unfortunately instead they shrink the menu tabs so that they are not visible.  Is there any way to have a configuration option that gives preference to the view tabs in constrained situations.

**Comment by FsxShader2012** [comment]
I would be very interested in this as well.

**Comment by FsxShader2012** [comment]
I found a way to circumvent this behaviour.
Take a look at the [State-Switch](https://github.com/thomasloven/lovelace-state-switch) and [Blank](https://github.com/jeremywillans/lovelace-blank-card) Cards.
In this example I used the browser width to determine if header cards should be shown:
```
header_cards:
  cards:
    - type: custom:state-switch
      entity: mediaquery
      states:
        '(min-width: 1500px)':
          type: markdown
          content: "Test"
        all:
          type: custom:blank-card      #Blank-Card because you need to define a type
```
You could also use [Browser Mod](https://github.com/thomasloven/hass-browser_mod) to decide on a device basis.
