### ISSUE TITLE
Make it work wiyhin a view

### ISSUE THREAD

**Issue by Tom-ahawk** [gadgetchnnel/lovelace-header-cards#6]
Nice card.
Please consider making a version so the "lovelace-header-cards" can be used in a view itself (as the views header) where the standard badges is located. This way the its easy to group badges and other things per view.

![image](https://user-images.githubusercontent.com/35527507/193452161-9eaf89af-432d-4e50-a511-eb35adcc5349.png)

**Comment by gadgetchnnel** [comment]
I have been considering per-view options for lovelace-header-cards so that the cards in the header can be different (or disabled) on a per view basis, but this is a bit different from what you are suggesting.

It is actually already possible to use cards as badges in a view, but this is undocumented and not supported in the UI so you need to use the raw editor to do it.

For example:
```
- title: Badge Test
   path: badgetest
   badges:
   - type: custom:mushroom-chips-card
      chips:
        - type: weather
           entity: weather.openweathermap
           show_conditions: true
           show_temperature: true
```
Will give you a view with a Mushroom Chips Card with a weather forecase chip as one of the badges for that view.
